- name: 'bug'
  color: 'B60205'
  description: '[RU] найдена ошибка; [EN] search bug'
- name: 'bugfix'
  color: 'B60205'
  description: '[RU] ошибка в предрелизе; [EN] bug pre-release'
- name: 'hotfix'
  color: 'B60205'
  description: '[RU] Критическая ошибка, которая исправиться в ближайшее время; [EN] Critical bug'
- name: 'question'
  color: '1D76DB'
  description: '[RU] Вопрос...; [EN] Question...'
- name: 'todo'
  color: '1D76DB'
  description: '[RU] Задача...; [EN] Todo...'
- name: 'suggestion'
  color: '1D76DB'
  description: '[RU] Предложение...; [EN] Suggestion...'
- name: 'client'
  color: 'C5DEF5'
  description: '[RU] issue от клиента; [EN] issue by client'
- name: 'team'
  color: 'C5DEF5'
  description: '[RU] issue от комманты; [EN] issue by team'
- name: 'accepted'
  color: '0E8A16'
  description: '[RU] Принято; [EN] Accepted'
- name: 'rejected'
  color: 'FBCA04'
  description: '[RU] Отклонено; [EN Rrejected'
- name: 'duplicate'
  color: 'C5DEF5'
  description: '[RU] Дубль; [EN Duplicate'
